## Linux
---
- hosts: aurora-linux-build-test
  tasks:
    - name: here we are using Ansible fetch module to copy file from remote machines to local.
      fetch:
        src: /home/ansible/tmp/files/test.txt
        dest: /etc/ansible/fetched

## Windows
- hosts: vm-didi-test
  tasks:
    - name: fetch file from remote machines to local - Windows OS.
      fetch:
        src: C:/tmp/test_copy.txt
        dest: /etc/ansible/fetched
